version: '2'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/code/app
    command:
      ["poetry", "run", "uvicorn", "--host", "0.0.0.0", "--port", "8000", "app.main:app", "--reload", "--reload-dir", "/code/app"]
    environment:
      - POSTGRES_USER=jie
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=hs4uc
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    ports:
      - 8000:8000
  db:
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_USER=jie
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=hs4uc
    ports:
      - 5433:5432
    volumes:
      - hs4uc:/var/lib/postgresql/data
volumes:
  hs4uc:
