"""add school category

Revision ID: 400975293af0
Revises: 9ea6729d0766
Create Date: 2024-11-29 11:56:01.042093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '400975293af0'
down_revision: Union[str, None] = '9ea6729d0766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('high_schools', sa.Column('category', sa.String(length=20), server_default='public', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('high_schools', 'category')
    # ### end Alembic commands ###
