"""add subrace to hs populations

Revision ID: 9ea6729d0766
Revises: b8e559e15732
Create Date: 2024-11-29 10:47:45.793193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea6729d0766'
down_revision: Union[str, None] = 'b8e559e15732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hs_populations', sa.Column('sub_race', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hs_populations', 'sub_race')
    # ### end Alembic commands ###
